"""empty message

Revision ID: f98f2f046b19
Revises: 
Create Date: 2023-09-21 15:53:42.415993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f98f2f046b19'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('my_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_title', sa.String(length=200), nullable=False),
    sa.Column('task_description', sa.String(length=200), nullable=True),
    sa.Column('task_status', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('my_tasks')
    # ### end Alembic commands ###
